# ---------------------------------------------------------------------
# This is a workflow to call the GitHub release notes creation workflow
# ---------------------------------------------------------------------
name: Call Create Github Release Notes

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'
  #push:
  #  branches:
  #    - master
  #    - boards/cubietruck
  #schedule:
  #    - cron: 0 8 * * 5

jobs:
  job1_Call_Create_Github_Release_Notes:
    name: Create Github Release Notes
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    #needs: job1_Build
    uses: mavenplugins/reusable-gh-actions/.github/workflows/__create_gh_release_notes.yml@master
    with:
      runner: ubuntu-latest
    secrets: inherit
